### ISSUE TITLE
Does PowerBuilder 10 & 12 supports the OpenID functions?

### ISSUE THREAD

**Issue by hakimnorizman** [bruce-armstrong/powerserver_openid#1]

**Comment by bruce-armstrong** [comment]
For the record, this is the PowerServer code.  The PowerBuilder code is in a new repository I just created:  https://github.com/bruce-armstrong/powerbuilder_openid

The sample, as written, would only work with rather recent versions of PowerBuilder.

- PowerBuilder 10 and 12 don't have the CrypterObject or CoderObject that were introduced by Appeon and are needed to generate the PKCE string.
- PowerBuilder 10 and 12 don't have the RestClient that was introduced by Appeon and is used to send the token request to the service.
- PowerBuilder 10 and 12 don't have the JsonParser object used to parse the token out of the token response

A PKCE string isn't required, and there are other ways to handle sending the REST requests and parsing the JSON response.  They would just require more work.   So it's possible do do in PowerBuilder 10 or 12.  I would recommend upgrading to a more recent version of PowerBuilder that has all those features rather than trying to hand code it though.
